### ISSUE TITLE
Maximum number of panels

### ISSUE THREAD

**Issue by blooop** [alesof/ROS2-VSC-Toolkit#3]
Is there a reason for limiting the number of panels to 4?

https://github.com/alesof/ROS2-VSC-Toolkit/blob/55321ae6674d9a2631fd3d89ea0a83ee1fdee619/src/extension.ts#L17

Could it be exposed as an option instead?

**Comment by alesof** [comment]
Hi blooop!

During the development an increasing number of panels was degrading performance, thus the enforcement on a max limit. It was already in my mind to provide a settings panel for such things but in the meantime I can expose it as an option for sure!

Thanks for the feedback ✌🏼

**Comment by blooop** [comment]
Great, thanks!

**Comment by alesof** [comment]
Hi there! Updating to the new version will provide you with a new command palette toggle to disable the panel limit 😃

**Comment by blooop** [comment]
Thanks for the quick update!
